/*
  Versión optimizada de la consulta:
  - Reemplaza DECODE por CASE para mejorar legibilidad.
  - Calcula una sola vez los valores por período en un CTE.
  - Reutiliza columnas derivadas para evitar lógica repetida.
*/
WITH base AS (
  SELECT
    t.*, 
    CASE curr_period
      WHEN '00' THEN FGBOPAL_00_YTD_ACTV
      WHEN '01' THEN FGBOPAL_01_YTD_ACTV
      WHEN '02' THEN FGBOPAL_02_YTD_ACTV
      WHEN '03' THEN FGBOPAL_03_YTD_ACTV
      WHEN '04' THEN FGBOPAL_04_YTD_ACTV
      WHEN '05' THEN FGBOPAL_05_YTD_ACTV
      WHEN '06' THEN FGBOPAL_06_YTD_ACTV
      WHEN '07' THEN FGBOPAL_07_YTD_ACTV
      WHEN '08' THEN FGBOPAL_08_YTD_ACTV
      WHEN '09' THEN FGBOPAL_09_YTD_ACTV
      WHEN '10' THEN FGBOPAL_10_YTD_ACTV
      WHEN '11' THEN FGBOPAL_11_YTD_ACTV
      WHEN '12' THEN FGBOPAL_12_YTD_ACTV
      WHEN '13' THEN FGBOPAL_13_YTD_ACTV
      WHEN '14' THEN FGBOPAL_14_YTD_ACTV
      ELSE 0
    END AS ytd_period,

    CASE curr_period
      WHEN '00' THEN FGBOPAL_00_ENCUMB
      WHEN '01' THEN FGBOPAL_01_ENCUMB
      WHEN '02' THEN FGBOPAL_02_ENCUMB
      WHEN '03' THEN FGBOPAL_03_ENCUMB
      WHEN '04' THEN FGBOPAL_04_ENCUMB
      WHEN '05' THEN FGBOPAL_05_ENCUMB
      WHEN '06' THEN FGBOPAL_06_ENCUMB
      WHEN '07' THEN FGBOPAL_07_ENCUMB
      WHEN '08' THEN FGBOPAL_08_ENCUMB
      WHEN '09' THEN FGBOPAL_09_ENCUMB
      WHEN '10' THEN FGBOPAL_10_ENCUMB
      WHEN '11' THEN FGBOPAL_11_ENCUMB
      WHEN '12' THEN FGBOPAL_12_ENCUMB
      WHEN '13' THEN FGBOPAL_13_ENCUMB
      WHEN '14' THEN FGBOPAL_14_ENCUMB
      ELSE 0
    END AS encumb_period,

    CASE curr_period
      WHEN '00' THEN FGBOPAL_00_BUD_RSRV
      WHEN '01' THEN FGBOPAL_01_BUD_RSRV
      WHEN '02' THEN FGBOPAL_02_BUD_RSRV
      WHEN '03' THEN FGBOPAL_03_BUD_RSRV
      WHEN '04' THEN FGBOPAL_04_BUD_RSRV
      WHEN '05' THEN FGBOPAL_05_BUD_RSRV
      WHEN '06' THEN FGBOPAL_06_BUD_RSRV
      WHEN '07' THEN FGBOPAL_07_BUD_RSRV
      WHEN '08' THEN FGBOPAL_08_BUD_RSRV
      WHEN '09' THEN FGBOPAL_09_BUD_RSRV
      WHEN '10' THEN FGBOPAL_10_BUD_RSRV
      WHEN '11' THEN FGBOPAL_11_BUD_RSRV
      WHEN '12' THEN FGBOPAL_12_BUD_RSRV
      WHEN '13' THEN FGBOPAL_13_BUD_RSRV
      WHEN '14' THEN FGBOPAL_14_BUD_RSRV
      ELSE 0
    END AS rsrv_period,

    CASE curr_period
      WHEN '00' THEN FGBOPAL_00_YTD_ACTV
      WHEN '01' THEN FGBOPAL_01_YTD_ACTV - FGBOPAL_00_YTD_ACTV
      WHEN '02' THEN FGBOPAL_02_YTD_ACTV - FGBOPAL_01_YTD_ACTV
      WHEN '03' THEN FGBOPAL_03_YTD_ACTV - FGBOPAL_02_YTD_ACTV
      WHEN '04' THEN FGBOPAL_04_YTD_ACTV - FGBOPAL_03_YTD_ACTV
      WHEN '05' THEN FGBOPAL_05_YTD_ACTV - FGBOPAL_04_YTD_ACTV
      WHEN '06' THEN FGBOPAL_06_YTD_ACTV - FGBOPAL_05_YTD_ACTV
      WHEN '07' THEN FGBOPAL_07_YTD_ACTV - FGBOPAL_06_YTD_ACTV
      WHEN '08' THEN FGBOPAL_08_YTD_ACTV - FGBOPAL_07_YTD_ACTV
      WHEN '09' THEN FGBOPAL_09_YTD_ACTV - FGBOPAL_08_YTD_ACTV
      WHEN '10' THEN FGBOPAL_10_YTD_ACTV - FGBOPAL_09_YTD_ACTV
      WHEN '11' THEN FGBOPAL_11_YTD_ACTV - FGBOPAL_10_YTD_ACTV
      WHEN '12' THEN FGBOPAL_12_YTD_ACTV - FGBOPAL_11_YTD_ACTV
      WHEN '13' THEN FGBOPAL_13_YTD_ACTV - FGBOPAL_12_YTD_ACTV
      WHEN '14' THEN FGBOPAL_14_YTD_ACTV - FGBOPAL_13_YTD_ACTV
      ELSE 0
    END AS ytd_current_period
  FROM FGBOPAL t
)
SELECT
  NVL(SUM(FGBOPAL_14_ADOPT_BUD), 0) AS adopted,
  NVL(SUM(FGBOPAL_14_BUD_ADJT), 0) AS adjustments,

  NVL(SUM(
    CASE
      WHEN curr_period = wk_last_period AND parm_accrual = 'Y'
        THEN (FGBOPAL_14_YTD_ACTV - FGBOPAL_13_YTD_ACTV)
      ELSE 0
    END + ytd_period
  ), 0) AS ytd_activity,

  NVL(SUM(
    CASE
      WHEN curr_period = wk_last_period AND parm_accrual = 'Y'
        THEN (FGBOPAL_14_ENCUMB - FGBOPAL_13_ENCUMB)
      ELSE 0
    END + encumb_period
  ), 0) AS encumbrance,

  NVL(SUM(
    CASE
      WHEN curr_period = wk_last_period AND parm_accrual = 'Y'
        THEN (FGBOPAL_14_BUD_RSRV - FGBOPAL_13_BUD_RSRV)
      ELSE 0
    END + rsrv_period
  ), 0) AS reservation,

  NVL(SUM(
    CASE
      WHEN curr_period = wk_last_period AND parm_accrual = 'Y'
        THEN (FGBOPAL_14_YTD_ACTV - FGBOPAL_13_YTD_ACTV)
      ELSE 0
    END + ytd_current_period
  ), 0) AS ytd_current_period
FROM base;
